services:
  - type: web
    name: astrokit-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --threads 2 web:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
    plan: free